# ─── 애플리케이션 기본 설정 ─────────
spring.application.name=mandooBot
server.port=8081

# ─── 데이터베이스 설정 ─────────────────────────────────────
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul

# ─── Postgres Dialect & Vector 설정 ──────────────────────────────────────────
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ─── OpenAI API 설정 ─────────────────────────────────────
spring.ai.openai.api-key=${OPENAI_API_KEY}
#spring.ai.openai.organization-id=${OPENAI_ORGANIZATION_ID}

# ─── RAG(Retrieval-Augmented Generation) 설정 ───────
chat.rag.distance.max=0.2
chat.rag.distance.limit=300

# ─── Redis ───────────────────
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.repositories.enabled=false

# ─── 최근 대화 컨텍스트 최대 턴 수 ─────
chat.history.max-turns=5

