# ─── 애플리케이션 기본 설정 ──────────────────────────────────────────
spring.application.name=mandooBot
server.port=8081

# ─── 데이터베이스 설정 ──────────────────────────────────────────
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Seoul
spring.datasource.url=jdbc:postgresql://${RDS_ENDPOINT}:5432/${DB_NAME}

# ─── Postgres Dialect & Vector 설정 ──────────────────────────────────────────
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ─── OpenAI API 설정 ──────────────────────────────────────────
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.embedding.options.model=text-embedding-ada-002
spring.ai.openai.chat.options.model=gpt-4.1
spring.ai.openai.chat.options.temperature=0.4
spring.ai.openai.chat.options.maxTokens=4000
spring.ai.openai.chat.options.topP=0.8
spring.ai.openai.chat.options.frequencyPenalty=0.0
spring.ai.openai.chat.options.presencePenalty=0.0

# ─── RAG(Retrieval-Augmented Generation) 설정 ───────────────────────────────────
chat.rag.distance.threshold=0.2

# ─── 채팅 히스토리 설정 ──────────────────────────────────────────
chat.history.max-turns=10
